defaults:
  - env: control_heading
  - agent: sac
  - callbacks: default
  - hydra: default
  - _self_

# Experiment-specific settings
project_name: FlyerRL
run_name: ControlDubinsHeading
total_timesteps: 1000000

env:
  params:
    render_mode: rgb_array
    max_episode_steps: 1000
    normalize_observations: false
    normalize_actions: false
    seed: ${seed}
    time_step: 0.0166667

# Global settings
use_wandb: True
resume_training: False
