# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build PyRust module
      uses: PyO3/maturin-action@v1.42.0
      with:
        command: build
        args: --release
        working-directory: ./pyflyer-rs
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo pip install pygame
        pip install -e .[deploy]
    - name: Install PyRust module
      run: |
        WHEEL_DIR=./pyflyer-rs/target/wheels
        for file in "$WHEEL_DIR"/*.whl
        do  
          WHEEL_FILE=$file
          echo The wheel file: $WHEEL_FILE
        done
        sudo pip install $WHEEL_FILE
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        pip install pytest-cov
        pytest --cov=./ --cov-report=xml