# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: on-prem build

on:
  push:
    branches: [ testing ]
  pull_request:
    branches: [ testing ]

jobs:
  build:

    runs-on: self-hosted
    
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        target: [x86_64]

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: "x64"
      env:
        AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo pip install pygame
        pip install -e .[deploy]
    - name: Build pyflyer-rs wheels
      uses: PyO3/maturin-action@v1.42.0
      with:
        target: ${{ matrix.target }}
        manylinux: auto
        args: --release --out dist -i 3.8 3.9 3.10 3.11
        working-directory: ./pyflyer-rs
    - name: Install pyflyer-rs wheels
      if: matrix.target == 'x86_64'
      run: |
        pip install pyflyer --no-index --find-links pyflyer-rs/dist --force-reinstall
        python -c "import pyflyer"
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        pip install pytest-cov
        pytest --cov=./ --cov-report=xml